src/main/resources/templates/login.html

Добавляем базовую страницу логирования.

Страница логирования

---

src/main/java/com/avito/controllers/simple/Login.java
src/main/java/com/avito/service/serviceRole/ServiceRole.java
src/main/java/com/avito/service/serviceRole/ServiceRoleImp.java
src/main/java/com/avito/service/serviceUser/ServiceUser.java
src/main/java/com/avito/service/serviceUser/ServiceUserImp.java
src/main/resources/templates/login.html

Service user and dao

---

src/main/java/com/avito/controllers/simple/Login.java
src/main/resources/templates/login.html

Login controller

---

src/main/resources/templates/index.html

need review margins on main page

adds margin

---

src/main/java/com/avito/controllers/simple/MainPage.java
src/main/java/com/avito/controllers/simple/MainPageController.java

need review controller for main page

creates main page controller

---

src/main/resources/templates/index.html

need review https://trello.com/c/T0Dzm3Et/26-%D0%BD%D0%B0-%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D0%BE%D0%B9-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D0%B5-%D0%B2-%D0%BA%D0%B0%D0%B6%D0%B4%D0%BE%D0%B9-%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D1%87%D0%BA%D0%B5-%D0%B4%D0%BE%D0%BB%D0%B6%D0%BD%D0%B0-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D1%82%D1%8C%D1%81%D1%8F-%D0%BA%D0%B0%D1%80%D1%82%D0%B8%D0%BD%D0%BA%D0%B0-%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D0%B0%D1%8F-%D0%BD%D0%B0%D1%85%D0%BE%D0%B4%D0%B8%D1%82%D1%81%D1%8F-%D0%B2-images

fix path to image placeholder

---

src/main/java/com/avito/controllers/simple/MainPageController.java

assigns url for main page controller

---

src/main/java/com/avito/controllers/rest/RoleRestController.java
src/main/java/com/avito/controllers/rest/UserRestController.java
src/main/java/com/avito/models/Role.java
src/main/java/com/avito/models/User.java
src/main/resources/application.yml

Rest controller

---

pom.xml
src/main/java/com/avito/models/Category.java

category model

---

src/main/java/com/avito/controllers/rest/UserRestController.java

маппинг на rest 200620 1249

---

src/main/java/com/avito/controllers/simple/LoginController.java

Переинован Login в LoginController 220620 1046

---

pom.xml
src/main/java/com/avito/configs/security/AuthProvider.java
src/main/java/com/avito/configs/security/CustomUserInfoTokenServices.java
src/main/java/com/avito/configs/security/SecurityConfig.java
src/main/java/com/avito/configs/security/UserDetailsServiceImpl.java
src/main/resources/application.yml

авторизация гугл 220620 2020

---

src/main/java/com/avito/controllers/rest/PostingRestController.java

need review fix posting controller

fix posting controller

---

src/main/java/com/avito/configs/DataInitializer.java
src/main/java/com/avito/dao/impl/RoleDaoImpl.java
src/main/java/com/avito/dao/interfaces/RoleDao.java
src/main/java/com/avito/service/impl/RoleServiceImpl.java
src/main/java/com/avito/service/interfaces/RoleService.java

encode-password

---

src/main/java/com/avito/configs/DataInitializer.java
src/main/java/com/avito/dao/impl/CategoryDaoImpl.java
src/main/java/com/avito/dao/impl/RoleDaoImpl.java
src/main/java/com/avito/dao/impl/UserDaoImpl.java
src/main/java/com/avito/service/impl/CategoryServiceImpl.java

deletes PlatformTransactionManager

---

src/main/resources/static/css/header-styles.css
src/main/resources/static/css/media/header-media.css
src/main/resources/static/js/header.js
src/main/resources/templates/fragments/header.html

Изменил внешний вид отображения языков. Теперь языки можно менять и иконка будет соответствовать после перезагрузки страницы. Так же теперь не нарушается адаптивность страницы

Update locale front

---

src/main/java/com/avito/configs/security/AuthProvider.java
src/main/java/com/avito/configs/security/UserDetailsServiceImpl.java
src/main/java/com/avito/controllers/rest/kladr/CityRestController.java
src/main/java/com/avito/controllers/rest/kladr/RegionRestController.java
src/main/java/com/avito/models/kladr/City.java
src/main/java/com/avito/service/impl/CityServiceImpl.java
src/main/java/com/avito/service/impl/RegionServiceImpl.java
src/main/java/com/avito/service/impl/RoleServiceImpl.java
src/main/java/com/avito/service/impl/SocialNetworkServiceImpl.java

refactoring autowired fields to private final

refactoring autowired fields to private final

---

src/main/java/com/avito/controllers/rest/CategoryRestController.java
src/main/java/com/avito/controllers/rest/PostingRestController.java
src/main/java/com/avito/controllers/rest/RoleRestController.java
src/main/java/com/avito/controllers/rest/UserRestController.java
src/main/java/com/avito/controllers/rest/kladr/CityRestController.java
src/main/java/com/avito/controllers/rest/kladr/RegionRestController.java
src/main/java/com/avito/dao/interfaces/RegionRepository.java
src/main/java/com/avito/service/impl/RegionServiceImpl.java
src/main/java/com/avito/service/interfaces/RegionService.java
src/main/resources/application.yml
src/main/resources/static/js/admin-page.js
src/main/resources/static/js/header.js
src/main/resources/static/js/posting.js

Две задачи:
1. Рефакторинк RestControllers
2. Во всех RestController обернуть возвращаемые значения в ResponseEntity

Fix resturl and responseentity

---

src/main/resources/static/js/main_page.js

Интернационализация кнопки "Перейти к объявлению".

Internationalize button "go to ad".

---

src/main/resources/static/js/header.js
src/main/resources/templates/fragments/header.html

Удаление неиспольуемого более кода в header.html и header.js

delete dead code

---

src/main/java/com/avito/models/Category.java
src/main/java/com/avito/models/User.java
src/main/java/com/avito/models/posting/Posting.java

Модель User. Добавила поле, которая содержит посты конкретного юзера.
@OneToMany(mappedBy = "user", cascade = {CascadeType.PERSIST, CascadeType.REMOVE}) //по умолчанию FetchType.LAZY
private Set<Posting> userPostings;
При удалении юзера будет происходить удаление его постов.
Модель Category. Добавила связь с постами в категории.
@OneToMany(mappedBy = "category",
cascade = {CascadeType.PERSIST, CascadeType.REMOVE})
private Set<Posting> postingsInCategory;
Модель Posting . Исправила связь с Category (раньше была @OneToOne)
Заменила на @ManyToOne - много постов может быть в одной категории
Выставила у полей User, Category fetch = FetchType.LAZY. По умолчанию он EAGER.

Models update

---

src/main/java/com/avito/configs/DataInitializer.java
src/main/java/com/avito/configs/security/AuthProvider.java
src/main/java/com/avito/configs/security/UserDetailsServiceImpl.java
src/main/java/com/avito/controllers/rest/UserRestController.java
src/main/java/com/avito/models/User.java
src/main/java/com/avito/repository/UserRepository.java
src/main/java/com/avito/service/impl/SocialNetworkServiceImpl.java
src/main/java/com/avito/service/impl/UserServiceImpl.java
src/main/java/com/avito/service/interfaces/UserService.java
src/main/resources/static/css/modal_reg.css
src/main/resources/static/js/modal_registation.js
src/main/resources/templates/fragments/header.html
src/main/resources/templates/main-page.html

регистрация пользователя с выпадающим меню

регистрация пользователя с выпадающим меню

---

pom.xml
src/main/java/com/avito/service/impl/EmailService.java
src/main/resources/application.properties

сервис почты

---

src/main/java/com/avito/controllers/simple/ResetPasswordController.java
src/main/java/com/avito/service/impl/EmailServiceIml.java
src/main/java/com/avito/service/interfaces/EmailService.java

Создан интерфейс EmailService и имплементировать EmailServiceImpl. Сделано рефакторинг по коду где должен быть задействован интерфейс

Создан интерфейс EmailService и имплементировать EmailServiceImpl. Сделано рефакторинг по коду где должен быть задействован интерфейс

---

src/main/resources/templates/fragments/header.html

fix logo link

---

src/main/java/com/board_of_ads/controllers/simple/PostingController.java
src/main/resources/static/css/posting.css
src/main/resources/static/js/header.js
src/main/resources/static/js/posting.js
src/main/resources/templates/fragments/header.html
src/main/resources/templates/posting.html

Изменил размер картинки нижнего блока слайдера
Страница постинг теперь загружается из базы и переход на нее можно делать с карточек на главной

Posting page fix links and slider

---

src/main/java/com/board_of_ads/controllers/simple/PostingController.java
src/main/resources/static/css/posting.css
src/main/resources/static/js/header.js
src/main/resources/static/js/posting.js
src/main/resources/templates/fragments/header.html
src/main/resources/templates/posting.html

Reverts Sidorenkomv/board-of-ads#129

Revert "Posting page fix links and slider"

---

src/main/java/com/board_of_ads/configs/DataInitializer.java
src/main/java/com/board_of_ads/controllers/rest/UserProfileRestController.java
src/main/java/com/board_of_ads/models/dto/ProfilePostingDTO.java
src/main/java/com/board_of_ads/models/posting/Posting.java
src/main/java/com/board_of_ads/models/posting/extra/PostingStatus.java
src/main/java/com/board_of_ads/models/posting/extra/PostingStatusStatistics.java
src/main/java/com/board_of_ads/repository/PostingRepository.java
src/main/java/com/board_of_ads/repository/PostingStatusRepository.java
src/main/java/com/board_of_ads/service/impl/PostingServiceImpl.java
src/main/java/com/board_of_ads/service/impl/PostingStatusServiceImpl.java
src/main/java/com/board_of_ads/service/interfaces/PostingService.java
src/main/java/com/board_of_ads/service/interfaces/PostingStatusService.java
src/main/resources/Dictionary.properties
src/main/resources/Dictionary_en.properties
src/main/resources/Dictionary_ru.properties
src/main/resources/static/css/user-profile/profile.css
src/main/resources/static/js/user_profile.js
src/main/resources/templates/user-profile.html

1) В Posting добавилось поле статус (сущность). (Активно, Архивно, Ожидает, На модерации)
2) На страницу профиля пользователя добавились группы со статусами. Появились картинки.
3) Добавил на страницу профиля 2 раздела - "Кошелек" и "Оплаченные услуги"

Объявления пользователя на странице профиля

---

src/main/resources/templates/admin-page.html

Убрал строку поиска и логотип Авито из админки

Убрал строку поиска и логотип Авито из админки

---

pom.xml
src/main/java/com/board_of_ads/configs/security/SecurityConfig.java
src/main/java/com/board_of_ads/controllers/auth/vkAuthController.java
src/main/resources/application.yml
src/main/resources/templates/fragments/header.html

Добавлена авторизация в ВКонтакте отдельным контроллером. 
В спринг-секьюрити пока что не интегрирована и не понятно нужно-ли интегрировать.

Авторизация ВКонтакте

---

src/main/java/com/board_of_ads/configs/security/SecurityConfig.java
src/main/java/com/board_of_ads/controllers/auth/VKoAuthController.java
src/main/java/com/board_of_ads/service/impl/OAuthNetworkServiceImpl.java
src/main/java/com/board_of_ads/service/interfaces/OAuthNetworkService.java

Замечания исправлены. Запросы из RestTemplate так же вынесены в сервис.

refactor 2

---

src/main/resources/static/js/user_avatar_canvas.js
src/main/resources/static/js/user_profile.js
src/main/resources/templates/user-profile.html

Рисует аватарку на странице профиля

Рисует аватарку на странице профиля

---

src/main/resources/static/css/header-styles.css
src/main/resources/static/images/small_arrow_down.svg
src/main/resources/static/js/header.js
src/main/resources/static/js/user_avatar_canvas.js
src/main/resources/static/js/user_profile.js
src/main/resources/templates/fragments/header.html
src/main/resources/templates/user-profile.html

Main page user avatar

---

src/main/resources/templates/fragments/header.html

Скрываем иконки сообщений и избранное от неавторизованного пользователя

Hide icon for anonimus user

---

src/main/java/com/board_of_ads/configs/DataInitializer.java
src/main/java/com/board_of_ads/controllers/rest/MessageRestController.java
src/main/java/com/board_of_ads/controllers/rest/PostingRestController.java
src/main/java/com/board_of_ads/models/Message.java
src/main/java/com/board_of_ads/models/User.java
src/main/java/com/board_of_ads/models/posting/Posting.java
src/main/java/com/board_of_ads/service/impl/MessageServiceImpl.java
src/main/java/com/board_of_ads/service/interfaces/MessageService.java

Фикс связей сущностей и сопутсвующее. 
В этом коммите работают связи между User, Posting, Message.
Требуется проверка прочих связей
@ManyToOne.

fix_link_entities

---

src/main/java/com/board_of_ads/configs/security/SecurityConfig.java
src/main/java/com/board_of_ads/controllers/rest/UserRestController.java
src/main/java/com/board_of_ads/service/impl/EmailServiceIml.java
src/main/java/com/board_of_ads/service/interfaces/EmailService.java
src/main/resources/application.yml

Сделать так чтобы на почту приходило письмо ввиде ссылки

Сделать так чтобы на почту приходило письмо ввиде ссылки

---

src/main/java/com/board_of_ads/controllers/simple/UserController.java
src/main/java/com/board_of_ads/models/PasswordResetToken.java
src/main/java/com/board_of_ads/service/impl/UserServiceImpl.java
src/main/java/com/board_of_ads/service/interfaces/UserService.java

Сделать токен на восстановление пароля одноразовым.

Сделать токен на восстановление пароля одноразовым.
